services:
  db:
    image: postgres:14
    env_file: .env
    networks:
      - mmost

  mmost:
    image: mattermost/mattermost-team-edition:release-5.39
    env_file: .env
    ports:
      - 8065:8065
      - 8067:8067
      - 8074:8074
      - 8075:8075
    volumes:
      - ./mattermost/config:/mattermost/config
    networks:
      - mmost


networks:
  mmost:
